PUZZLES = [
    {
        "key": "Lloc",
        "prompt": "Sabotatge 1: Lloc?",
        "answers": ["Taleia"],
        "media_type": "audio",
        "media": "audio_sab1.mp3",
        "hint": "Començar per T",
        "placeholder": "Lloc",
    },
    {
        "key": "Mes",
        "prompt": "Sabotatge 2: A quin mes?",
        "answers": ["Juliol"],
        "media_type": "img",
        "media": "img_sabmes.jpg",
        "hint": "Prime numbers.",
        "placeholder": "mes de l'any",
    },
    {
        "key": "Dia",
        "prompt": "Sabotatge 3: Quin dia?",
        "answers": ["11"],
        "media_type": "img",
        "media": "img_sabdia.jpg",
        "hint": "Si no tens gana... Tens?",
        "placeholder": "Són 2 digits...",
    },
    {
        "key": "Hora",
        "prompt": "Sabotatge 4: A quina hora?",
        "answers": ["18:00"],
        "media_type": "img",
        "media": "img_sabhora.png",
        "hint": "Si no tens gana... Tens?",
        "placeholder": "Hora en format XX:XX",
    },
]