PUZZLES = [
    {
        "key": "Hora",
        "prompt": "El Tastet té una mania molt peculiar... Els Mitjons!!<br>N'ha deixat alguns tant foradats que semblen coladors.",
        "answers": ["18:00"],
        "media_type": "img",
        "media": "img_sabhora.jpeg",
        "hint": "Conta el número de forats... Els mitjons van per separat",
        "placeholder": "Hora en format XX:XX",
    },
    {
        "key": "Dia",
        "prompt": "Últimament el Tastet fa forats per tot arreu... i aquest cop no n'ha fet pas pocs!",
        "answers": ["11"],
        "media_type": "img",
        "media": "img_sabdia.jpg",
        "hint": "Per tot arreu!",
        "placeholder": "Format en 2 dígits XX",
    },
    {
        "key": "Mes",
        "prompt": "Entre els llibres, hem trobat un recull de dites i refranys catalans.<br>Però algú ho ha manipulat!<br>Algunes paraules estan ratllades.",
        "answers": ["Juliol"],
        "media_type": "img",
        "media": "img_sabmes.jpg",
        "hint": "No és el Gener.",
        "placeholder": "Mes de l'any. (Primera lletra majúscula)",
    },
    {
        "key": "Lloc",
        "prompt": "El Tastet porta uns dies bordant sempre igual, què deu voler dir?",
        "answers": ["Taleia"],
        "media_type": "audio",
        "media": "audio_sab1.mp3",
        "hint": "Utilitza el codi morse.",
        "placeholder": "Lloc. (Primera lletra majúscula)",
    },
]